feat: add k8s adapter
spacecloud-io/space-cloud pull request #1639
Opened 2023-01-29 07:15 UTC by shubham4443

Fixes #1633

2023-01-29 13:42 UTC, YourTechBud requested changes

2023-01-29 13:42 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +	factory := dynamicinformer.NewFilteredDynamicSharedInformerFactory(dc, 5*time.Minute, v1.NamespaceAll, nil)
```suggestion
	factory := dynamicinformer.NewFilteredDynamicSharedInformerFactory(dc, 5*time.Minute, namespace, nil)
```

2023-01-29 13:42 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +				}
Make this a helper function `addOrUpdateConfig`

2023-01-29 13:42 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +				}
Put in function `addOrUpdateOldConfig`

2023-01-29 13:42 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +				k.configurationN[key] = s
I suggest you use this method to remove to minimize allocs 
```golang
func remove(s []int, i int) []int {
    s[i] = s[len(s)-1]
    return s[:len(s)-1]
}
```

2023-01-29 13:42 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +func (k *K8s) toRaw() ([]byte, error) {
Rename to `getCaddyConfig()`

2023-01-29 16:56 UTC, shubham4443 commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +				k.configurationN[key] = s
this method doesn't work when length is 1

2023-01-30 03:00 UTC, YourTechBud approved these changes

2023-01-30 03:01 UTC, merged