create configman list api
spacecloud-io/space-cloud pull request #1652
Opened 2023-02-11 15:57 UTC by shubham4443

Signed-off-by: Shubham Nazare <shubham4443@gmail.com>

Fixes #1635 

Creating CRUD APIs for sources in configman.

2023-02-12 10:34 UTC, YourTechBud requested changes

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/run/run.go
> +			err := configman.InitializeConfigLoader()
You can combine the if and this line

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/adapter.go
>  	"github.com/spacecloud-io/space-cloud/managers/configman/common"
Sc imports should be on a separate line

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/operations.go
> +func (k *K8s) List(gvr schema.GroupVersionResource) ([]*unstructured.Unstructured, error) {
Use the lock to update `k.configuration` map as well

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/managers/configman/common/http.go
> +	"github.com/spacecloud-io/space-cloud/managers/source"
Organise the imports

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/managers/source/operations.go
> +	moduleName = moduleName[7:]
Instead of this use `strings.TrimPrefix(moduleName, "source.")`

2023-02-12 10:34 UTC, YourTechBud commented on sc-poc/managers/configman/operations.go
> +func List(gvr schema.GroupVersionResource) ([]*unstructured.Unstructured, error) {
This should return the object in the same format k8s would

2023-02-12 12:04 UTC, shubham4443 commented on sc-poc/managers/configman/operations.go
> +func List(gvr schema.GroupVersionResource) ([]*unstructured.Unstructured, error) {
Can we change ConfigType from `map[string][]*unstructured.Unstructured` to `map[string]*unstructured.UnstructuredList`? What are you thoughts on this?

2023-02-12 12:39 UTC, YourTechBud commented on sc-poc/managers/configman/operations.go
> +func List(gvr schema.GroupVersionResource) ([]*unstructured.Unstructured, error) {
I suggest we keep the ConfigType the same but return back the response as `*unstructured.UnstructuredList`

2023-02-15 17:35 UTC, shubham4443 commented
Changing the status of PR from draft to ready to merge as all the operations are successfully added.

2023-02-16 14:12 UTC, YourTechBud requested changes

2023-02-16 14:12 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +	lock          sync.RWMutex
Lets keep the lock as the first parameter in the struct

2023-02-16 14:12 UTC, YourTechBud commented on sc-poc/managers/configman/common/http.go
> +	"github.com/spacecloud-io/space-cloud/managers/source"
Sc imports should be last

2023-02-16 14:12 UTC, YourTechBud commented on sc-poc/managers/configman/common/http.go
> +		for _, unstr := range v {
I suggest we don't loop here. It will create multiple routes

2023-02-16 14:41 UTC, shubham4443 commented on sc-poc/managers/configman/common/http.go
> +		for _, unstr := range v {
I didn't understand. How can I create the `Get` and `Delete` route for each source?

2023-04-09 06:19 UTC, YourTechBud requested changes

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/adapter.go
> +	Apply(schema.GroupVersionResource, *unstructured.Unstructured) error
We don't need `schema.GroupVersionResource` for apply. You can generate it from the object to be applied. We can still choose to keep it if you want.

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/file/file.go
> +	Path          string
Why is this exported?

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/file/file.go
> +	return f.configuration, nil
Don't return `f.configuration` directly. First acquire a read lock, make a copy of f.configuration and then return it. I suggest you put the above in a function named `readConfig`. Return it directly can still result in a data race condition

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/file/operations.go
> +	arr, err := utils.ReadSpecObjectsFromFile(filepath.Join(f.Path, fileName))
Do we really need to read the file again? We already have a configuration object stored, why not just delete from there and overwrite the file. We can consider deleting the file if the length of configuration for that gvr becomes 0.

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/helpers.go
> +	return k.configuration
Return a new copy here.
```suggestion
	return k.copyConfig()
```

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +				newConfig := k.copyConfig()
```suggestion
				newConfig := k.getConfig()
```

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/k8s/k8s.go
> +	newConfig := k.copyConfig()
```suggestion
	newConfig := k.getConfig()
```

2023-04-09 06:19 UTC, YourTechBud commented on sc-poc/managers/configman/common/http.go
> +	for k := range config {
We should add a `/v1/config/openapi.json` route for returning the openapi doc for config changes as well. Make this as a seperate issue that you can fix in a separate PR

2023-04-09 07:14 UTC, shubham4443 commented on sc-poc/managers/configman/common/http.go
> +	for k := range config {
I didn't understand this

2023-04-09 07:16 UTC, shubham4443 commented on sc-poc/managers/configman/common/http.go
> +	for k := range config {
We already have a route for returning the openapi doc

2023-04-12 19:12 UTC, YourTechBud requested changes

2023-04-12 19:12 UTC, YourTechBud commented on sc-poc/managers/configman/adapter/file/helpers.go
> +	return f.configuration
Create a new copy in a temp variable and return that

2023-04-14 11:24 UTC, YourTechBud approved these changes

2023-04-14 11:24 UTC, merged