feat: generate golang client
spacecloud-io/space-cloud pull request #1664
Opened 2023-03-21 05:52 UTC by shubham4443

Fixes #1662

2023-04-09 06:29 UTC, YourTechBud requested changes

2023-04-09 06:29 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/generate.go
> +			_ = viper.BindPFlag("lan", cmd.Flags().Lookup("lan"))
Rename to `lang`

2023-04-09 06:29 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/generate.go
> +			lan := viper.GetString("lan")
rename variable to `lang`

2023-04-09 06:29 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/generate.go
> +	cmd.Flags().StringP("lan", "l", "go", "Language in which to generate code. Supported languages are RTK, Go")
```suggestion
	cmd.Flags().StringP("lan", "l", "go", "Language in which to generate code. Supported languages are 'rtk', 'go'")
```

2023-05-14 08:41 UTC, YourTechBud requested changes

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/generate.go
> +				pkgName := "openapi"
Lets make this configurable with the --package flag

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/api.go
> +func NewClient(server string) (*Client, error) {
Instead of taking a string param named `server`. Take the following:
```go
type RequestEditorFn func(ctx context.Context, req *http.Request) error
type ClientConfig struct {
  BaseURL string
  Middlewares []MiddlewareFn
}
```
Middleware func is something you need to call before firing any request. [Ref](https://github.com/deepmap/oapi-codegen/blob/master/examples/petstore-expanded/petstore-client.gen.go#L380)

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/api.go
> +		s += fmt.Sprintf("func (c *Client) %s(ctx context.Context, %s) (*%s, error) {\n", opName, paramsArg, opName+"Response")
The response should not be the response object directly. instead it should be a struct having the following methods
- Raw() -> Returns http.Response (response.Body should still be readable. [Ref](https://stackoverflow.com/a/39792097)) 
- StatusCode() -> Returns the status code
- Result() -> Returns the struct you made if the status code was 200; This fn should only be available if openapi declared a 200 response code
- ResultXXX() -> Object for that status code (eg: `Result500`). struct name for these objects should be like `<OperationID>Response<Status>`

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/api.go
> +		if p.Value.Schema.Value.Type == "object" {
```suggestion
		if p.Value.Content != nil && utils.StringExists(p.Value.Content["application/json"].Schema.Value.Type, "object", "array") {
```

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +	responseSchema := operation.Responses["200"].Value.Content["application/json"].Schema
As mentioned earlier, Create a struct for each response code

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +			typeName := parent + "_" + child
```suggestion
			typeName := name + "_" + child
```

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +			typeName := parent + "_" + child
```suggestion
			typeName := name + "_" + child
```

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +func generateTypeDef(schema *openapi3.SchemaRef, name string, parent string) string {
I dont think we need `parent` or `parentMapping`

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +			}
```suggestion
			if !required {
				k += ",omitempty"
			}
```

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +				s += fmt.Sprintf("%s `json:%q`\n", arrayType, k)
Cannot use array type here since it has values corresponding to jsonschema types (eg, `number`, `integer`, `boolean`).
We should make a function to convert jsonschema primitives to golang primitives

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +			if arrayType == "object" {
WHat if its an array of array i.e. 2d array?

2023-05-14 08:41 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +		case "integer", "number":
Number cannot be int32. number should be float

2023-05-25 13:54 UTC, shubham4443 commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +func generateTypeDef(schema *openapi3.SchemaRef, name string, parent string) string {
It is used to avoid making long struct names for nested object fields. So in case of nested object fields, the object name is preceded by only its parent and not the entire ancestor. Let me know if it still needs to be removed.

2023-05-30 18:15 UTC, YourTechBud commented on sc-poc/cmd/spacectl/commands/client/generate/golang/types.go
> +func generateTypeDef(schema *openapi3.SchemaRef, name string, parent string) string {
I have solved this in my other suggestions

2023-06-18 02:34 UTC, YourTechBud approved these changes

2023-06-18 05:52 UTC, YourTechBud commented
Merged in #1694

2023-06-18 05:52 UTC, closed without merging