[Feature] Added pubsub support using watermill
spacecloud-io/space-cloud pull request #1667
Opened 2023-04-11 12:24 UTC by khannaabhi

2023-04-12 19:20 UTC, YourTechBud requested changes

2023-04-12 19:20 UTC, YourTechBud commented on sc-poc/modules/pubsub/app.go
> +	return nil
Ypu need to destroy/ remove the key from the usage pool here

2023-04-12 19:20 UTC, YourTechBud commented on sc-poc/modules/pubsub/connectors/connectors.go
> +	PubSubClient *gochannel.GoChannel
Don't export this directly. Make a method to return this

2023-04-12 19:20 UTC, YourTechBud commented on sc-poc/modules/pubsub/operations.go
> +func (a *App) SendAckNack(messageID string, ack bool) error {
Remove this

2023-04-12 19:20 UTC, YourTechBud commented on sc-poc/modules/pubsub/operations.go
> +				"type":                 "object",
Key should be `APIManMsg`. Its value will be the json schema object

2023-04-12 19:20 UTC, YourTechBud commented on sc-poc/modules/pubsub/operations.go
> +						"$ref": "#/components/messages/MyPayload",
Rename `MyPayload` to `APIManMsg`

2023-04-14 11:19 UTC, YourTechBud requested changes

2023-04-14 11:19 UTC, YourTechBud commented on sc-poc/modules/pubsub/app.go
> +}
Add interface guards

2023-04-14 11:19 UTC, YourTechBud commented on sc-poc/modules/pubsub/connectors/connectors.go
> +		watermill.NewStdLogger(false, false),
Is it possible to use caddy;s logger here?

2023-04-14 11:19 UTC, YourTechBud commented on sc-poc/modules/pubsub/app.go
> +	connector := val.(*connectors.Connector)
Set the logger here if watermill can use caddy's logger

2023-04-15 05:36 UTC, khannaabhi commented on sc-poc/modules/pubsub/connectors/connectors.go
> +		watermill.NewStdLogger(false, false),
no the methods are not same

2023-04-15 12:13 UTC, merged