feat!: add websocket interface for pubsub
spacecloud-io/space-cloud pull request #1670
Opened 2023-04-16 15:21 UTC by shubham4443

Fixes #1668
The PR adds the ability to perform publish/subscribe operations with the websocket protocol.

2023-04-16 16:35 UTC, YourTechBud requested changes

2023-04-16 16:35 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +	apis := []*apis.API{}
I suggest we make this api in `Provision` and simply return it here

2023-04-16 16:35 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +			go func() {
I don't think we need to run this as a seperate goroutine.

You can confirm this by starting a subscriber then trying to reload the config. If the config gets reloaded without affecting the socket we are good.

2023-04-16 16:35 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +							pubMsg.ID = uuid.NewString()
Use ksuid

2023-04-16 16:35 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +			for {
This implementation won't work cause it doesn't leave room for you to check for the unsubscribe event that could come in next

2023-04-16 16:57 UTC, shubham4443 commented on sc-poc/modules/pubsub/websocket.go
> +			for {
Should we use a variable which stores the state(subscribed/not subscribed) in which the client is in right now?

2023-04-18 07:57 UTC, YourTechBud requested changes

2023-04-18 07:57 UTC, YourTechBud commented on sc-poc/modules/pubsub/types.go
Export `eventType` and the various constants

2023-04-19 14:52 UTC, merged