Add support RSA secrets
spacecloud-io/space-cloud pull request #1675
Opened 2023-04-22 06:24 UTC by prithvi081099

#1654

2023-04-23 07:51 UTC, shubham4443 commented on sc-poc/modules/auth/helpers.go
>  	// TODO: Return private key here
We can remove this comment

2023-04-23 08:12 UTC, shubham4443 commented on sc-poc/manifests/example/auth_secret.yaml
rename this file as `auth_secret_hsa.yaml`

2023-04-23 08:12 UTC, shubham4443 commented on sc-poc/modules/auth/helpers.go
>  	// TODO: Return private key here
we can remove this comment now

2023-04-23 08:12 UTC, shubham4443 commented on sc-poc/modules/auth/helpers.go
>  	// TODO: Return public key here
remove this comment

2023-04-24 06:35 UTC, shubham4443 commented on sc-poc/modules/auth/helpers.go
> +			return b
for HSA, secret.Value is a string. So this type assertion fails and hence this returns nil. So type assert this with string instead of []byte then return it as []byte(secret.Value)

2023-04-24 06:35 UTC, shubham4443 commented on sc-poc/modules/auth/types/jwt.go
> +		Value interface{}
Remove Value and instead add privateKey, publicKey fields. for HSA, both fields will have same value.

2023-04-25 06:51 UTC, shubham4443 approved these changes

2023-05-14 08:54 UTC, YourTechBud requested changes

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/auth_secret_rsa.go
> +	PrivateValue string `json:"private,omitempty"`
I suggest we make these of type `*SecretSource` instead of `string`. lets add a `Value` in `SecretSource` struct which can correspond to the string value we are using here. Make similar change for HSA
```suggestion
	// PublicKey holds the value of the public key
	PublicKey *SecretSource `json:"publicKey"`

	// PrivateKey holds the value of the private key
	// +kubebuilder:validation:Optional
	PrivateKey *SecretSource `json:"privateKey,omitempty"`
```

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/auth_secret_rsa.go
> +	ValueFrom *SecretSource `json:"valueFrom,omitempty"`
We can remove this

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/modules/auth/helpers.go
>  	return nil
No need of any if condition. Simply return `secret.PrivateKey`

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/modules/auth/helpers.go
>  	return nil
Simply return `secret.PublicKey`

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/go.sum
> +github.com/golang-jwt/jwt v3.2.2+incompatible/go.mod h1:8pz2t5EyA70fFQQSrl6XZXzqecmYZeUEB8OUGHkxJ+I=
Why are we using this version. We should ideally be using v4

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/sources/auth/jwthsasecret/source.go
> +		PrivateKey: s.Spec.Value,
```suggestion
		PublicKey:  []byte(s.Spec.Secret.Value),
		PrivateKey: []byte(s.Spec.Secret.Value),
```

2023-05-14 08:54 UTC, YourTechBud commented on sc-poc/sources/auth/jwtrsasecret/source.go
> +		log.Fatal(err)
No need to do this

2023-05-27 05:52 UTC, YourTechBud requested changes

2023-05-27 05:52 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/auth_secret_hsa.go
> +	Secret *SecretSource `json:"secret,omitempty"`
This cannot be a pointer or omitempty or optional

2023-05-27 05:52 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/auth_secret_rsa.go
> +	PrivateKey *SecretSource `json:"privateKey,omitempty"`
This can be empty and optional. Public key is required

2023-06-18 05:59 UTC, YourTechBud commented
Fixed via #1695

2023-06-18 05:59 UTC, closed without merging