Add pubsub source and schema validation
spacecloud-io/space-cloud pull request #1679
Opened 2023-05-10 06:06 UTC by shubham4443

Fixes #1672

2023-05-14 09:09 UTC, YourTechBud requested changes

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/operations.go
>  				"APIManMsg": map[string]interface{}{
Remove this if its no longer needed

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/types.go
> +	Schema   map[string]*v1alpha1.ChannelSchema `json:"schema,omitempty"`
```suggestion
	Schema   *v1alpha1.ChannelSchema `json:"schema,omitempty"`
```

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +	channelSchema.Properties = channel.Payload.Schema
```suggestion
	channelSchema := channel.Payload.Schema
```

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +						b, _ := json.Marshal(errMsgs)
Make a proper error struct. Something like:

```go
type WebsocketErrorMessage struct {
    Message string `json:"message" // This will be human readable error message like `Payload of invalid format provided`
    Errors []string `json:"errors,omitempty"`
}
```

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
> +						b, _ := json.Marshal(errMsgs)
Also make sure we add this to the `subscribe` part of the `producerChannel` in `AsyncAPI`

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/websocket.go
>  					if err != nil {
```suggestion
					if err := a.Publish(channel.Name, pubMsg, PublishOptions{}); err != nil {
```

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/pubsub_channel.go
> +	Properties map[string]*ChannelSchema `json:"properties,omitempty"`
Put AdditionalProperties as well which can be `json.RawMessage` (interface{})

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/pubsub_channel.go
> +	Payload map[string]*ChannelSchema `json:"payload,omitempty"`
```suggestion
	Payload *ChannelSchema `json:"payload,omitempty"`
```

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/modules/pubsub/app.go
> +		channelSrc := src.(*pubsub_channel.PubsubChannelSource)
Make an interface in this package itself

2023-05-14 09:09 UTC, YourTechBud commented on sc-poc/sources/pubsub_channel/source.go
> +	_ source.Source = (*PubsubChannelSource)(nil)
This should implement an interface

2023-05-14 14:47 UTC, shubham4443 commented on sc-poc/manifests/crds/core.space-cloud.io_compiledgraphqlsources.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
Can you guide me how to do it? I built controller-gen binary from the source itself and this is what it generates.

2023-05-14 16:53 UTC, YourTechBud requested changes

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/modules/pubsub/app.go
> +		channelSrc := src.(Source)
Check if its okay. Continue if it isnt

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/modules/pubsub/asyncapi.go
> +							Name:        "Error",
```suggestion
							Name:        "PublishError",
```

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/modules/pubsub/asyncapi.go
> +									"message": map[string]interface{}{
Accept a message id as well. We need to tell the publisher which message didn't publish. Also you can make json schema directly from a struct without having to make such maps. Look at this library: https://github.com/invopop/jsonschema

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/modules/pubsub/types.go
> +	Message string   `json:"message"`
Add `ID` for message id

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/sources/pubsub_channel/source.go
> +	_ source.Source = (*PubsubChannelSource)(nil)
You missed this

2023-05-14 16:53 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/pubsub_channel.go
> +	Payload *ChannelSchema `json:"payload,omitempty"`
This is not creating a proper crd i guess... Can we making this a map ehich we can then mapstructure decode?

2023-05-25 13:24 UTC, shubham4443 commented on sc-poc/modules/pubsub/asyncapi.go
> +									"message": map[string]interface{}{
Can we do this in a separate PR? I will make an issue for it.

2023-05-27 05:03 UTC, YourTechBud commented on sc-poc/modules/pubsub/asyncapi.go
> +									"message": map[string]interface{}{
Ok

2023-05-27 05:08 UTC, YourTechBud requested changes

2023-05-27 05:08 UTC, YourTechBud commented on sc-poc/modules/pubsub/asyncapi.go
> +							Name:        "PublishError",
Can we merge publish error with the `Acknowledge` message?

2023-05-27 05:08 UTC, YourTechBud commented on sc-poc/manifests/crds/core.space-cloud.io_compiledgraphqlsources.yaml
> +    controller-gen.kubebuilder.io/version: (devel)
Download the latest kubebuilder version from the releases section on GitHub.

2023-05-30 19:18 UTC, YourTechBud requested changes

2023-05-30 19:18 UTC, YourTechBud commented on sc-poc/modules/pubsub/asyncapi.go
> +					OneOf: []MessageEntity{
No need of a oneOf if you are returning just a single object

2023-06-02 13:08 UTC, shubham4443 commented on sc-poc/modules/pubsub/asyncapi.go
> +									"message": map[string]interface{}{
https://github.com/spacecloud-io/space-cloud/issues/1680

2023-06-17 10:42 UTC, YourTechBud approved these changes

2023-06-17 10:42 UTC, merged