[Feature]: Added support to load openapi source and create rpcs for e…
spacecloud-io/space-cloud pull request #1696
Opened 2023-06-18 11:54 UTC by khannaabhi

…ach operation in openapi spec

2023-06-20 06:36 UTC, YourTechBud requested changes

2023-06-20 06:36 UTC, YourTechBud commented on sc-poc/Makefile
> +install-deps:
Add this command in `.PHONY`

2023-06-20 06:36 UTC, YourTechBud commented on sc-poc/pkg/apis/core/v1alpha1/source_openapi.go
> +	Ref *HTTPOptions `json:"ref,omitempty"`
Add kubebuilder comments for optional

2023-06-20 06:36 UTC, YourTechBud commented on sc-poc/sources/openapi/helpers.go
> +		},
No need for this

2023-06-20 06:36 UTC, YourTechBud commented on sc-poc/sources/openapi/source.go
> +	wg     *sync.WaitGroup
I don't think you need this

2023-06-20 06:36 UTC, YourTechBud commented on sc-poc/sources/openapi/source.go
> +		if postSpec := pathSpec.Post; postSpec != nil {
Can we make this code DRY?

2023-07-01 05:32 UTC, khannaabhi commented on sc-poc/sources/openapi/helpers.go
> +		},
We need this or else we all the rpc will be exposed as POST endpoint. Is that the expected behavior?

2023-07-05 08:56 UTC, YourTechBud commented on sc-poc/sources/openapi/helpers.go
> +		},
Yes

2023-07-05 08:59 UTC, YourTechBud commented on sc-poc/sources/openapi/helpers.go
> +		if method != http.MethodGet {
```suggestion
		if method != http.MethodGet || method != http.MethodDelete {
```

2023-07-05 09:00 UTC, YourTechBud commented on sc-poc/sources/openapi/helpers.go
> +		},
```suggestion
	return &rpc.RPC{
		Name:           operationID,
		OperationType:  operationType,
		RequestSchema:  reqSchema,
		ResponseSchema: respSchema,
```

2023-07-05 09:02 UTC, YourTechBud approved these changes

2023-07-05 09:02 UTC, merged